(defun raiz (a b c)
(let* ((delta (- (expt b 2) (* 4 a c)))
         (denom (* 2 a))
        )
    (if (< delta 0)
        ;; raízes complexas
        (let* ((parte-real (/ (- b) denom))
               (parte-img (/ (sqrt (- delta)) denom)); sqrt de valor positivo (abs(delta))
               (parte-real-str (format nil "~a" parte-real))
               (parte-img-str(format nil "~a" parte-img))
               ) 
          (list (format nil "~a + ~ai" parte-real-str parte-img-str)
                (format nil "~a - ~ai" parte-real-str parte-img-str)
          )
        )
        ;; raízes reais
        (let ((x1 (/ (+ (- b) (sqrt delta)) denom))
              (x2 (/ (- (- b) (sqrt delta)) denom))
              )
          (list x1 x2)
        )
    )
)
)