(defun my-last (L)
    (if (null (cdr L))
        L
        (my-last (cdr L))
    )
)

(defun my-but-last (L)
    (if (null (cdr (cdr L)))
        L 
        (my-but-last (cdr L))
    )
)

(defun my-element-at (L N)
    (dotimes (i (- N 1) L)
        (setf L (cdr L))
    )
    (car L)
)

(defun my-length (L &optional (i 0))
    (if (null L)
        i
        (my-length (cdr L) (+ i 1))
    )
)

(defun my-reverse (L &optional (reversed '()))
    (if (null L)
        reversed
        (my-reverse (cdr L) (cons (car L) reversed))
    )
)

(defun my-duplicate (L &optional (result '()))
    (if (null L)
        (reverse result)
        (my-duplicate (cdr L) (cons (car L) (cons (car L) result)))
    )   
)

(defun my-replicate (L N &optional (result '()))
    (if (null L)
        (reverse result)
        (let ((temp '()))
            (dotimes (i N temp)
                (setf temp (cons (car L) temp))
            )
            (my-replicate (cdr L) N (append temp result))
        )
    )
)

(defun my-drop (L N &optional (result '()) (i 1))
    (if (null L)
        (reverse result)
        (if (= (mod i N) 0)
            (my-drop (cdr L) N result (+ i 1))
            (my-drop (cdr L) N (cons (car L) result) (+ i 1))
        )
    )
)

(defun my-split (L N &optional (result1 '()) (result2 '()) (i 1))
    (if (null L)
        (list (my-reverse result1) (my-reverse result2))
        (if (> i N)
            (my-split (cdr L) N result1 (cons (car L) result2) (+ i 1))
            (my-split (cdr L) N (cons (car L) result1) result2 (+ i 1))
        )
    )
)

(defun my-rotate (L N)
    (apply #'append (my-reverse (my-split L N)))
)

(defun my-slice (L I J)
    (car (my-split (car (cdr (my-split L (- I 1)))) (+ (- J I) 1)))
)

(defun my-remove-at (L N &optional (result '()) (i 1))
    (if (null L)
        (reverse result)
        (if (= i N)
            (my-drop (cdr L) N result (+ i 1))
            (my-drop (cdr L) N (cons (car L) result) (+ i 1))
        )
    )
)

(defun my-insert-at (elemento L N &optional (result '()) (i 1))
    (if (null L)
        (reverse result)
        (if (= i N)
            (my-insert-at elemento (cdr L) N (cons (car L) (cons elemento result)) (+ i 1))
            (my-insert-at elemento (cdr L) N (cons (car L) result) (+ i 1))
        )
    )
)